### ISSUE TITLE
replyWithInvoice not defined

### ISSUE THREAD

**Issue by jbest2015** [n1try/telegram-payment-bot#2]
Trying to run this demo .. getting the following error when i choose the product. 
ReferenceError: replyWithInvoice is not defined
      at app.hears (C:\Users\jb\Source\Repos\GridLockBot2\index.js:52:9)
      at Promise.resolve.then (C:\Users\jb\Source\Repos\GridLockBot2\node_modules\telegraf\composer.js:93:56)
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by vrumger** [comment]
Your probably missing `ctx`
```js
ctx.replyWithInvoice(createInvoice(p));
```

**Comment by jbest2015** [comment]
Thank you , I could've swore I tried that , but I tried again and it worked. Thank you.

**Comment by vrumger** [comment]
👌
